---
- hosts: all
  become: yes
  tasks: 
  - name: installing looping concept
    apt:
     name: "{{ item }}" 
     state: present
  with_items:
  - git
  - tree
  - wget
  when: ansible_os_family =="Debian"